### ISSUE TITLE
OSS License?

### ISSUE THREAD

**Issue by coord-e** [kaz/kiritan-voice#1]
Hi, We may want to re-use the code in this repository (maybe with modification) for our (possibly OSS) project. If it is OK for us, I want you to set a license for this repository.

If you intend not to permit re-distribution, we'd be appreciated if you state that explicitly. (and sorry for this misunderstanding issue)

**Comment by kaz** [comment]
I've added license statements. See https://github.com/kaz/kiritan-voice/blob/master/LICENSE.
Thank you for your interests in this repository.
